"""This code has generated by AutoTK.
date:2022-12-27 16:03:06.021108 """

import tkinter as tk


class Login:
    def __init__(self, win):
        """initials all the widgets"""
        self.win = win
        self.win.config(bg="blue")
        self.headline = tk.Label(self.win,
                                 text="L O G I N   P A G E", fg="red", border="1", bg="blue",
                                 font=("Fixedsys", 20, "bold"))
        self.can = tk.Canvas(self.win,
                             height="200", width="200", bg="lightblue", border="1")
        self.email_label = tk.Label(self.can,
                                    text="Email:", fg="black", border="1", bg="lightblue", font=("Modern", 15, "bold"))
        self.password_label = tk.Label(self.can,
                                       text="Password:", fg="black", border="1", bg="lightblue",
                                       font=("Modern", 15, "bold"))
        self.email_field = tk.Entry(self.can,
                                    bg="lightblue", font=("Modern", 12, "bold"), width="15", border="0")
        self.var_6 = tk.Canvas(self.can,
                               height="2", width="100", bg="red", border="1")
        self.var_67 = tk.Canvas(self.can,
                                height="2", width="100", bg="red", border="1")
        self.password_fioeld = tk.Entry(self.can,
                                        bg="lightblue", font=("Modern", 12, "bold"), width="15", border="0")
        self.var_8 = tk.Button(self.win,
                               text="LOGIN", bg="lightgreen", border="1", fg="black", font=("none", 12, "bold"),
                               width="20", height="1", command=self.var_8_onclick)
        self.var_89 = tk.Button(self.win,
                                text="SIGN UP", bg="lightgreen", border="1", fg="black", font=("none", 12, "bold"),
                                width="20", height="1", command=self.var_89_onclick)
        self.var_10 = tk.Canvas(self.can,
                                width="50", height="50", bg="lightblue")

        self.var_10.create_oval(0, 0, 50, 50, fill="red")
        self.var_1011 = tk.Canvas(self.can,
                                  width="50", height="50", bg="lightblue")

        self.var_1011.create_oval(0, 0, 50, 50, fill="red")
        self.var_101112 = tk.Canvas(self.can,
                                    width="50", height="50", bg="lightblue")

        self.var_101112.create_oval(0, 0, 50, 50, fill="red")
        self.var_10111213 = tk.Canvas(self.can,
                                      width="50", height="50", bg="lightblue")

        self.var_10111213.create_oval(0, 0, 50, 50, fill="red")
        self.var_14 = tk.Checkbutton(self.win,
                                     text="keep me login", bg="blue",  border="1", fg="white",
                                     font=("none", 10, "bold"), command=self.var_14_onclick)
        self.var_15 = tk.Canvas(self.win,
                                height="20", width="20", bg="red", border="0")
        self.var_1516 = tk.Canvas(self.win,
                                  height="20", width="20", bg="red", border="0")
        self.var_151617 = tk.Canvas(self.win,
                                    height="20", width="20", bg="red", border="0")
        self.var_15161718 = tk.Canvas(self.win,
                                      height="20", width="20", bg="red", border="0")
        self.var_1516171819 = tk.Canvas(self.win,
                                        height="20", width="20", bg="red", border="0")
        self.var_151617181920 = tk.Canvas(self.win,
                                          height="20", width="20", bg="red", border="0")
        self.var_21 = tk.Text(self.win,
                              bg="lightblue", width="10", height="5", font=("none", 10, "normal"))
        self.var_22 = tk.Label(self.win,
                               text="note", fg="white", border="1", bg="blue", font=("none", 10, "normal"))

    def place_widgets(self):
        """placing all the widgets"""
        self.headline.place(x=88, y=7)
        self.can.place(x=144, y=81)
        self.email_label.place(x=29, y=29)
        self.password_label.place(x=26, y=105)
        self.email_field.place(x=37, y=59)
        self.var_6.place(x=48, y=161)
        self.var_67.place(x=47, y=78)
        self.password_fioeld.place(x=37, y=139)
        self.var_8.place(x=145, y=295)
        self.var_89.place(x=144, y=335)
        self.var_10.place(x=-28, y=-20)
        self.var_1011.place(x=185, y=-17)
        self.var_101112.place(x=-25, y=175)
        self.var_10111213.place(x=180, y=175)
        self.var_14.place(x=365, y=296)
        self.var_15.place(x=44, y=66)
        self.var_1516.place(x=81, y=297)
        self.var_151617.place(x=40, y=251)
        self.var_15161718.place(x=80, y=200)
        self.var_1516171819.place(x=80, y=106)
        self.var_151617181920.place(x=42, y=153)
        self.var_21.place(x=389, y=119)
        self.var_22.place(x=411, y=88)

    def var_8_onclick(self):
        print("var_8 Clicked!")
        # your code here...
        ...

    def var_89_onclick(self):
        print("var_89 Clicked!")
        # your code here...
        ...

    def var_14_onclick(self):
        print("var_14 Clicked!")
        # your code here...
        ...


if __name__ == '__main__':
    root = tk.Tk()
    gui = Login(root)
    root.geometry('500x500')
    gui.place_widgets()
    root.mainloop()
